### ISSUE TITLE
4.24

### ISSUE THREAD

**Issue by Ashrindy** [modio/modio-ue4#1]
Can this please support ue4 4.24 version? The legacy version is giving me errors.
Cheers
Ashrindy

**Comment by stephenwhittle** [comment]
Hi!

At this time there are no plans to back-port the new UE4 plugin to versions below UE 4.25, as our forthcoming crossplatform support relies on plugin features that were released on that engine version. 
However, I did do a quick test - if you only require Windows support, you could change the unreal version number in the uplugin file, and you'd need to make changes to a few of the C++ functions in `ModioConvert.h` to avoid some template errors that occur in 4.24 - namely you'd need to alter the overloads of `ToUnreal` that operate on `std::vector`s so they aren't ambiguous with the overload handling bitflags coming from the underlying native SDK. 
There may be other changes required - as I said, I only had time for a quick evaluation - but, if you don't require support for other platforms and updating to a newer version of the engine is out of the question, it might get you over the line with minimal effort.
