### ISSUE TITLE
UE5 support upcoming? 

### ISSUE THREAD

**Issue by r614** [modio/modio-ue4#2]
Hey folks!

Just wanted to reach out and see if there's planned support for Unreal Engine 5. 
We are starting a new project, and would love to have integrations with the engine :)

**Comment by stephenwhittle** [comment]
Hello!
It's on our roadmap for this quarter, we'll be sure to announce when it's available!

**Comment by r614** [comment]
Awesome, thanks! :)

**Comment by stephenwhittle** [comment]
Early access UE5 support is now available in the current release, please feel free to provide feedback here or in the mod.io Discord :)
